# Generated by Django 5.1.1 on 2024-09-10 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('synopsis', models.TextField(default='synopsis')),
                ('image', models.ImageField(default=1, upload_to='')),
                ('description', models.TextField(default='description')),
                ('genre', models.CharField(default='genre', max_length=255)),
            ],
            options={
                'db_table': 'cat_table',
            },
        ),
        migrations.CreateModel(
            name='Current',
            fields=[
                ('cur_id', models.AutoField(primary_key=True, serialize=False)),
                ('curr_read', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appblog.category')),
            ],
            options={
                'db_table': 'current_table',
            },
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('fav_id', models.AutoField(primary_key=True, serialize=False)),
                ('fav_read', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appblog.category')),
            ],
            options={
                'db_table': 'fav_table',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('recommend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appblog.category')),
            ],
            options={
                'db_table': 'recommendation_table',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('rev_id', models.AutoField(primary_key=True, serialize=False)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appblog.category')),
            ],
            options={
                'db_table': 'review_table',
            },
        ),
        migrations.CreateModel(
            name='Tbr',
            fields=[
                ('tbr_id', models.AutoField(primary_key=True, serialize=False)),
                ('toread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appblog.category')),
            ],
            options={
                'db_table': 'blogtable',
            },
        ),
        migrations.CreateModel(
            name='Wrapup',
            fields=[
                ('mon_id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appblog.category')),
            ],
            options={
                'db_table': 'wrapup_table',
            },
        ),
    ]
