# Generated by Django 5.1.1 on 2024-09-25 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
