# Generated by Django 5.1.1 on 2024-10-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0005_alter_category_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='about',
            field=models.TextField(default='about'),
        ),
        migrations.AddField(
            model_name='category',
            name='prof_img',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
