# Generated by Django 5.1.1 on 2024-10-04 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0006_category_about_category_prof_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourites',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appblog.review'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appblog.review'),
        ),
        migrations.AddField(
            model_name='wrapup',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appblog.review'),
        ),
    ]
