# Generated by Django 5.1.1 on 2024-10-07 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0009_remove_category_about_remove_category_prof_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourites',
            old_name='review',
            new_name='rev_mod',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='review',
            new_name='rev_mod',
        ),
        migrations.RenameField(
            model_name='wrapup',
            old_name='review',
            new_name='rev_mod',
        ),
    ]
